name: amc_new
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter_svg:
  flutter_icons: ^1.1.0
  material_design_icons_flutter: 4.0.5755
  flutter_swiper: ^1.1.6
  flutter:
    sdk: flutter
  http: ^0.12.0
  json_annotation: ^3.1.0
  retrofit: any




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  url_launcher: ^5.0.3
  simple_url_preview: ^0.1.10
  get_it: ^1.0.3+2
  image_picker: ^0.6.7+4
  flutter_secure_storage:
  logger: 
  flutter_spinkit: "^4.1.2"
  fluttertoast: 
  flutter_local_notifications: 
  flutter_downloader: ^1.4.4
  permission_handler: 4.4.0+hotfix.2
  ext_storage: ^1.0.3
  dio:
  advance_pdf_viewer:
  downloads_path_provider_28:
  open_file:
  path_provider:
  
 

dev_dependencies:
  flutter_config: 
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.5.0
  retrofit_generator: any
  




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/epic-lanka-logo.png
    - assets/profile.png
    - assets/WhatsApp Image 2021-01-02 at 23.28.16.jpeg
    - assets/WhatsApp Image 2021-01-02 at 23.28.17 (1).jpeg
    - assets/WhatsApp Image 2021-01-02 at 23.28.17.jpeg
    - assets/support.jpg
    - assets/facebook.svg
    - assets/telephone.svg
    - assets/email.svg
    - assets/call-center.svg
    - assets/world-wide-web.svg
    - assets/edit0.jpg
    - assets/edit1.jpg
    - assets/edit2.jpg
    - assets/edit3.jpg
    - assets/edit4.jpg
    - assets/edit5.jpg
    - assets/report.svg
    - assets/invoice.svg
    - assets/right.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Redressed-Regular
      fonts:
        - asset: fonts/Redressed-Regular.ttf
    - family: BerkshireSwash
      fonts:
        - asset: fonts/BerkshireSwash-Regular.ttf
    - family: Lateef
      fonts:
        - asset: fonts/Lateef-Regular.ttf
    - family: Rancho
      fonts:
        - asset: fonts/Rancho-Regular.ttf
    - family: Advent_Pro
      fonts:
        - asset: fonts/AdventPro-Regular.ttf
        
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
